### ISSUE TITLE
jsonlint not found

### ISSUE THREAD

**Issue by andersennl** [AtomLinter/linter-jsonlint#10]
I'm following the setup guide but can't get jsonlint to work. Here is what I do:
`apm install linter-jsonlint`
`which jsonlint # => jsonlint not found`
I've tried this several times after uninstalling it before.

In fact, the weird thing is, it worked a day ago after installing it the first time. I suspect this has something to do with how I started Atom, like from the command line or by double clicking the Atom icon. At least this makes a difference for Rubocop to work or not. 

What am I missing? Thanks!

**Comment by willpracht** [comment]
By default, I believe *linter-jsonlint* points to a local version of *jsonlint*.

If you want to point to a global install, you'll have to first install it globally:

```bash
npm i jsonlint -g
```

Then grab the path:

```bash
which jsonlint
```

Then use that in the settings.

However, both scenarios fail to work for me lately. Not sure what the problem is.

**Comment by 1000ch** [comment]
Now only `apm install linter-jsonlint` to install this.
