### ISSUE TITLE
Options?

### ISSUE THREAD

**Issue by dodekeract** [AtomLinter/linter-jsonlint#35]
Is there any way I could force my JSON to be indented with tabs? Or that the keys must be sorted?

**Comment by 1000ch** [comment]
Now linter-jsonlint uses Node API of jsonlint which does not contain an interface to pass options. :( To accept options, linter-jsonlint has to use CLI instead of Node API of jsonlint or jsonlint has to implement Node API to accept options.

**Comment by Arcanemagus** [comment]
So after looking over the CLI code, it appears that all of the options you are talking about relate to the _output_ of your JSON that it does after validating, and have nothing to do with the actual linting of the JSON, so the reason the Node API doesn't have support for those is that the options actually have no bearing on the checking that `jsonlint` does :frowning:.

For reference, from what I can tell here is what the CLI options _really_ do:

* `--sort-keys`: (Attempts to) sort the keys _before_ validation for some reason...
* `--in-place`: Pretty accurate current description, overwrites the file after parsing with the modified output
* `--indent CHAR`: Use this character to indent the _output_ after validation
* `--compact`: Disables running a `console.log(e)` on the error
* `--validate`: The only option really missing from the Node API: Allows validating the JSON against a schema, could be worked around simply if we really wanted since this just calls [JSV](https://github.com/garycourt/JSV)
* `--environment`: Passed into JSV, no bearing on the JSON validation
* `--quiet`: Exactly what it says, doesn't print the JSON to the output
* `--forcePrettyPrint`: Exactly what it says, try to force pretty printing the output

**Comment by Arcanemagus** [comment]
Marking as invalid since those options don't actually have any bearing on the results, support for that should be added to `jsonlint` itself. (Unfortunately development of that seems to be rather... stagnant.)
